add version checkt to ci 2

diff --git a/.github/workflows/new_ci.yml b/.github/workflows/new_ci.yml
--- a/.github/workflows/new_ci.yml
+++ b/.github/workflows/new_ci.yml
@@ -80,3 +80,83 @@ jobs:
             exit 1
           fi
           echo "Version format is ok"
+      # Get cluster_structure version
+      - name: Checkout the cluster_structure branch to get its version
+        uses: actions/checkout@v4
+        with:
+          ref: cluster_structure
+      - name: Get version from cluster_structure branch
+        id: cluster_structure_version
+        run: |
+          if [[ "$(git show origin/cluster_structure:cloelib/observables/clusters/__init__.py)" == *"__version__"* ]]; then
+            MAIN_VERSION="$(grep -oP '__version__ = "\K[^"]+' cloelib/observables/clusters/__init__.py)"
+          else
+            echo "No version found at cluster_structure, assuming version 0.0.0"
+            MAIN_VERSION="0.0.0"
+          fi
+          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV
+      # Compare
+      - name: Check version update
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          IFS=. read -r C1 C2 C3 <<< "$CURRENT_VERSION"
+          IFS=. read -r M1 M2 M3 <<< "$MAIN_VERSION"
+          if [ "$C1" != "$M1" ]; then
+            GOAL="$((M1 + 1)).0.0"
+            if [ $C1 -lt $M1 ]; then
+              ERROR="  - Version number should increase: $CURRENT_VERSION<$PREVIOUS_VERSION"
+            elif [ "$C1" != "$((M1 + 1))" ]; then
+              ERROR="  - Increment should be done by 1: $GOAL"
+            elif [ "$CURRENT_VERSION" != "$GOAL" ]; then
+              ERROR="  - When major version is increased, others should be zero: $GOAL"
+            fi
+          elif [ "$C2" != "$M2" ]; then
+            GOAL="$C1.$((M2 + 1)).0"
+            if [ $C2 -lt $M2 ]; then
+              ERROR="  - Version number should increase: $CURRENT_VERSION<$PREVIOUS_VERSION"
+            elif [ "$C2" != "$((M2 + 1))" ]; then
+              ERROR="  - Increments should be done by 1: $GOAL"
+            elif [ "$CURRENT_VERSION" != "$GOAL" ]; then
+              ERROR="  - When middle version is increased, last number should be zero: $GOAL"
+            fi
+          elif [ "$C3" != "$M3" ]; then
+            GOAL="$C1.$C2.$((M3 + 1))"
+            if [ $C3 -lt $M3 ]; then
+              ERROR="  - Version number should increase: $CURRENT_VERSION<$PREVIOUS_VERSION"
+            elif [ "$CURRENT_VERSION" != "$GOAL" ]; then
+              ERROR="  - Increments should be done by 1: $GOAL"
+            fi
+          else
+            ERROR="  - Version at cloelib/observables/clusters/__init__.py has not been updated!"
+          fi
+          if [ "$ERROR" != "" ]; then
+            echo "Check failed:"
+            echo "$ERROR"
+            echo "#################"
+            echo "Removing version from PR title: $NEW_TITLE"
+            curl -s -X PATCH \
+              -H "Authorization: token $GITHUB_TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              -d "{\"title\":\"$NEW_TITLE\"}" \
+              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" > /dev/null
+            exit 1
+          fi
+          echo "[ok] Version increased changed!"
+      # Add version number to PR title
+      - name : Make new title for PR
+        run: |
+          NEW_TITLE="${NEW_TITLE} [cluster-version:$CURRENT_VERSION] (cloe-org:$CLOE_ORG_TAG)"
+          echo "New title: $NEW_TITLE"
+          echo "NEW_TITLE=$NEW_TITLE" >> $GITHUB_ENV
+      - name: Update PR title
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # Use the GitHub API to update the PR title
+          echo "Updating PR #$PR_NUMBER with new title: $NEW_TITLE"
+          curl -s -X PATCH \
+            -H "Authorization: token $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            -d "{\"title\":\"$NEW_TITLE\"}" \
+            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" > /dev/null
